import type { Metadata } from 'next'
import './globals.css'
import { DM_Sans } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const DMsans = DM_Sans({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="ligth">
      <body className={DMsans.className}>{children}</body>
    </html>
  )
}
